# Generated by Django 2.2.4 on 2019-08-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('image', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('sensors', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('remarks', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('brand', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('model', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
