# Generated by Django 2.2.4 on 2019-10-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalog',
            name='alive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
